using System.Reflection;
using System.Runtime.CompilerServices;

// Version/FileVersion/InformationalVersion are generated by the SDK from MSBuild
// properties so they can be release-driven (see MacMirrorReceiver.csproj and
// scripts/publish-win-x64.ps1). The identity attributes below stay hand-authored.
[assembly: AssemblyCompany("iMirror")]
[assembly: AssemblyConfiguration("Release")]
[assembly: AssemblyProduct("iMirror")]
[assembly: AssemblyTitle("iMirror")]
[assembly: InternalsVisibleTo("MacMirrorReceiver.Tests")]
// TargetPlatform/SupportedOSPlatform ("Windows7.0") are generated by the SDK from the
// net8.0-windows target framework, so they are no longer declared here.
